version: "3"
services:
  test_mysql:
    image: mysql:latest
    container_name: test_mysql
    restart: always
    ports:
      - "3385:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: metrics
    volumes:
    - ./docker/mysql/initdb/:/docker-entrypoint-initdb.d/

  test_phpmyadmin:
    image: phpmyadmin:latest
    links:
      - test_mysql:db
    ports:
      - "85:80"
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
      PMA_ABSOLUTE_URI: http://pma.local
